import 'package:flutter/material.dart';

import '../models/streaming_platform.dart';

class StreamingPlatforms with ChangeNotifier {
  StreamingPlatform? selectedStreamingPlatform;

  final List<StreamingPlatform> _streamingPlatform = [
    StreamingPlatform(
      id: 'netflix',
      name: 'Netflix',
      logoUrl: 'assets/images/netflix_logo.png',
      supportedCountries: [
        "ar",
        "at",
        "au",
        "be",
        "br",
        "ca",
        "ch",
        "cl",
        "co",
        "cz",
        "de",
        "dk",
        "ec",
        "ee",
        "es",
        "fi",
        "fr",
        "gb",
        "gr",
        "hu",
        "id",
        "ie",
        "in",
        "it",
        "jp",
        "kr",
        "lt",
        "lv",
        "mx",
        "my",
        "nl",
        "no",
        "nz",
        "pe",
        "ph",
        "pl",
        "pt",
        "ro",
        "ru",
        "se",
        "sg",
        "th",
        "tr",
        "us",
        "ve",
        "za",
      ],
      totalCountries: 46,
    ),
    StreamingPlatform(
      id: 'prime',
      name: 'Prime Video',
      logoUrl: 'assets/images/prime_logo.png',
      supportedCountries: [
        "ae",
        "ar",
        "at",
        "au",
        "az",
        "be",
        "bg",
        "br",
        "ca",
        "ch",
        "cl",
        "cy",
        "cz",
        "de",
        "dk",
        "ee",
        "es",
        "fi",
        "fr",
        "gb",
        "gr",
        "hk",
        "ie",
        "il",
        "in",
        "is",
        "it",
        "jp",
        "lv",
        "md",
        "mk",
        "mx",
        "nl",
        "no",
        "nz",
        "pa",
        "ph",
        "pl",
        "pt",
        "ro",
        "rs",
        "ru",
        "se",
        "sg",
        "th",
        "tn",
        "tr",
        "ua",
        "us",
        "vn",
        "za",
      ],
      totalCountries: 51,
    ),
    StreamingPlatform(
      id: 'disney',
      name: 'Disney+',
      logoUrl: 'assets/images/disney_logo.png',
      totalCountries: 23,
      supportedCountries: [
        "ar",
        "at",
        "au",
        "be",
        "br",
        "ca",
        "ch",
        "cl",
        "co",
        "de",
        "dk",
        "es",
        "fi",
        "fr",
        "gb",
        "it",
        "mx",
        "nl",
        "no",
        "nz",
        "pt",
        "se",
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'apple',
      name: 'Apple TV+',
      logoUrl: 'assets/images/apple_logo.png',
      totalCountries: 45,
      supportedCountries: [
        "ae",
        "ar",
        "at",
        "au",
        "az",
        "be",
        "bg",
        "br",
        "ca",
        "ch",
        "cl",
        "cy",
        "cz",
        "de",
        "dk",
        "ee",
        "es",
        "fi",
        "fr",
        "gb",
        "gr",
        "hk",
        "ie",
        "il",
        "in",
        "it",
        "jp",
        "lv",
        "md",
        "mx",
        "nl",
        "no",
        "nz",
        "pa",
        "ph",
        "pl",
        "pt",
        "ru",
        "se",
        "sg",
        "th",
        "ua",
        "us",
        "vn",
        "za",
      ],
    ),
    StreamingPlatform(
      id: 'mubi',
      name: 'Mubi',
      logoUrl: 'assets/images/mubi_logo.png',
      totalCountries: 49,
      supportedCountries: [
        "ae",
        "ar",
        "at",
        "au",
        "az",
        "be",
        "bg",
        "br",
        "ca",
        "ch",
        "cl",
        "cy",
        "de",
        "dk",
        "ee",
        "es",
        "fi",
        "fr",
        "gb",
        "gr",
        "hk",
        "ie",
        "il",
        "in",
        "it",
        "jp",
        "lv",
        "md",
        "mk",
        "mx",
        "nl",
        "no",
        "nz",
        "pa",
        "ph",
        "pl",
        "pt",
        "ro",
        "rs",
        "ru",
        "se",
        "sg",
        "th",
        "tn",
        "tr",
        "ua",
        "us",
        "vn",
        "za",
      ],
    ),
    StreamingPlatform(
      id: 'hbo',
      name: 'HBO Max',
      logoUrl: 'assets/images/hbo_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'hulu',
      name: 'Hulu',
      logoUrl: 'assets/images/hulu_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'paramount',
      name: 'Paramount',
      logoUrl: 'assets/images/paramount_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'peacock',
      name: 'Peacock',
      logoUrl: 'assets/images/peacock_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'showtime',
      name: 'Showtime',
      logoUrl: 'assets/images/showtime_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
    StreamingPlatform(
      id: 'starz',
      name: 'Starz',
      logoUrl: 'assets/images/starz_logo.png',
      totalCountries: 1,
      supportedCountries: [
        "us",
      ],
    ),
  ];

  List<StreamingPlatform> get streamingPlatform {
    return [..._streamingPlatform];
  }

  StreamingPlatform findStreamingPlatformById(String id) {
    return _streamingPlatform.firstWhere((platform) => platform.id == id);
  }

  StreamingPlatform findStreamingPlatformByName(String? name) {
    return _streamingPlatform.firstWhere((platform) => platform.name == name);
  }

  void initializeSelectedSteamingPlatform() {
    selectedStreamingPlatform = _streamingPlatform[0];
  }

  void setNewSelectedSteamingPlatformByName(String? name) {
    StreamingPlatform newSelectedValue = findStreamingPlatformByName(name);
    selectedStreamingPlatform = newSelectedValue;
    print(selectedStreamingPlatform?.name);
  }
}
