final Map<String, String> countries = {
  "ae": "United Arab Emirates",
  "ar": "Argentina",
  "at": "Austria",
  "au": "Australia",
  "az": "Azerbaijan",
  "be": "Belgium",
  "bg": "Bulgaria",
  "br": "Brazil",
  "ca": "Canada",
  "ch": 'Switzerland',
  "cl": "Chile",
  "co": "Colombia",
  "cy": "Cyprus",
  "cz": "Czechia",
  "de": "Germany",
  "dk": "Denmark",
  "ec": "Ecuador",
  "ee": "Estonia",
  "es": "Spain",
  "fi": "Finland",
  "fr": "France",
  "gb": "United Kingdom",
  "gr": "Greece",
  "hk": "Hong Kong",
  "hu": "Hungary",
  "id": "Indonesia",
  "ie": "Ireland",
  "il": "Israel",
  "in": "India",
  "is": "Iceland",
  "it": "Italy",
  "jp": "Japan",
  "kr": "South Korea",
  "lt": "Lithuania",
  "lv": "Latvia",
  "md": "Moldova",
  "mk": "North Macedonia",
  "mx": "Mexico",
  "my": "Malaysia",
  "nl": "Netherlands",
  "no": "Norway",
  "nz": "New Zealand",
  "pa": "Panama",
  "pe": "Peru",
  "ph": "Philipine",
  "pl": "Poland",
  "pt": "Portugal",
  "ro": "Romania",
  "rs": "Serbia",
  "ru": "Russia",
  "se": "Sweden",
  "sg": "Singapore",
  "th": "Thailand",
  "tn": "Tunisia",
  "tr": "Turkey	",
  "ua": "Ukraine",
  "us": "United States",
  "vn": "Vietnam",
  "za": "South Africa	",
};
